name: 'DogeOps to the mooooooooon 🚀'
author: 'Carlos Gonzalez <carlos.gonzalez@with-madrid.com>'
description: 'Upload a doge.yaml manifest to a DogeOps endpoint.'

inputs:
  manifest:
    description: "Name of the manifest file"
    default: "doge.yaml"

runs:
  using: 'docker'
  image: 'WITH-Test/dogeops-action/dogeops-action'
