name: Build and publish a Docker image to ghcr.io
on:

  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - *

jobs:
  lint:
    uses: WITH-Test/workflows/.github/workflows/lint-python.yml@main

  docker_publish:
    needs: lint
    if: {{ github.event_name == 'release' || github.repo.ref == 'refs/heads/main' }}
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2

      - name: lowercase repo
        run: |
          echo "GHCR_REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@v8
        with:
          image_name: ${{ env.GHCR_REPO }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
